name: Export Confluence Space 
on:
   workflow_dispatch:
jobs:
 export-space:
    runs-on:ubuntu-latest
        env:
          AUTH: ${{ secrets.EMAIL }}:${{ secrets.APITOKEN }}
        run: |
          ENCODED_AUTH=$(echo -n "$AUTH" | base64)

          echo "=== Ejecutando curl ==="
          RESPONSE=$(curl -s -w "\nHTTP_CODE:%{http_code}" -o response.json -X POST "https://${{ secrets.DOMAIN }}/wiki/rest/api/longtask/export/space" \
            -H "Authorization: Basic $ENCODED_AUTH" \
            -H "Content-Type: application/json" \
            -d "{\"spaceKey\":\"${{ secrets.SPACEKEY }}\",\"exportType\":\"xml\"}")

          echo "=== Resultado HTTP ==="
          echo "$RESPONSE"

          echo "=== Cuerpo de respuesta ==="
          cat response.json || echo "response.json no existe"

           

        
